harvester:
    image: cord/dhcpharvester
    container_name: harvester
    restart: never
    labels:
        - "lab.cord.component=Controller"
    volumes:
        - "/var/lib/maas/dhcp:/dhcp"
        - "/etc/bind/maas:/bind"
        - "/home/ubuntu/compose-services/dhcpharvester/key:/key"
    ports:
        - "8954:8954"
    command: [ "--server", "192.168.42.231", "--port", "954", "--key", "/key/mykey.conf", "--zone", "cord.lab", "--update", "--verify", "--timeout", "1s", "--repeat", "5m", "--quiet", "2s", "--workers", "10", "--filter", "^" ]
